services:
  admin_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curs_admin_app
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://localhost:8000
      NUXT_PUBLIC_SITE_URL: http://localhost:3001
    ports:
      - "3001:3000"
